### ISSUE TITLE
能否给出权重系列来源

### ISSUE THREAD

**Issue by ivysrono** [breakwa11/GoAIRatings#3]
官权 ELF LeelaMaster 等系列我知道来源，但肯定有人不清楚。
ZQ 系列我就不知道从哪来的。
不知能否加个来源链接。

**Comment by breakwa11** [comment]
ELF可以加上引用，LeelaMaster 已经有引用了，你可以在 [AIcmd.md](https://github.com/breakwa11/GoAIRatings/blob/master/AIcmds.md) 里找到更详细的说明
其它都是来自少数几个QQ群，由于没有在github或类似地方公开，没有办法做引用，我也在考虑这些权重找个网盘放进去做引用

**Comment by ivysrono** [comment]
https://github.com/breakwa11/GoAIRatings/blob/master/AIcmds.md#leela-zero-015
金毛有基于 0.16 的引擎的：https://github.com/yenw/LeelaZero_PhoenixGo/releases
或者你列的项目有新版：https://github.com/alreadydone/lz/releases/tag/phoenix-v0.33

https://github.com/breakwa11/GoAIRatings/blob/master/AIcmds.md#leelazero-with-elf-opengo-network
这里的 ELF v0 的下载地址请统一为 https。

https://github.com/breakwa11/GoAIRatings/blob/master/AIcmds.md#mogo-windows
这个地址也有HTTPs：https://www.godrago.net/Engines.htm

**Comment by breakwa11** [comment]
已全部更改

**Comment by ivysrono** [comment]
minigo 的命名需要加上 v15 v16 这种标注说明，否则很快就要搞不清的，每代都有 000199.
还有资源有限 v15 就先测 939 和 990 这两个最强的吧。
另外，bjiyxo 后来训练的 15b 权重，为了简明可辨，建议如下命名：
[bjiyxo 15b-194-152k quantized](https://zero.sjeng.org/networks/8b28fe3c8df08d879dc70cbba9a8d2d3e56f4dce6cbab2e1e289851f24044288.gz) 

[bjiyxo 15b-195-184k quantized](https://zero.sjeng.org/networks/92297ff22dfa781bd02def6cadafdf7d69e9546300a913faf19e6164b895ed39.gz) 

[bjiyxo 15b-196-88k quantized](https://zero.sjeng.org/networks/8b23a0eae19c688c3aff1d506a957c9140574fb739b635002fcec8bfc8cf3b3a.gz) 

[bjiyxo 15b-198-232k quantized](https://zero.sjeng.org/networks/12c1d7d28773757c4c6a5fa3b1f0acba5781254b525b7a254a83289a313e8029.gz) 

[bjiyxo 15b-199-96k quantized](https://zero.sjeng.org/networks/f438268ef88e083aaf7a08fba885552818abc08cd0aefce9671954a8df3cf707.gz) 

[bjiyxo 15b-199-240k quantized](https://zero.sjeng.org/networks/83f1bb325920fc1c4866672f5ddd4a4364f3e0f1557fdd6115a6e2d8142d2563.gz)

PS 看了眼参数详情，有的用的 gz 格式，有的用的 txt 格式。虽然都能识别，但我测试下来 gz 格式要慢 5% 左右。仅供参考。

**Comment by scaomath** [comment]
Is it possible to add a download link for `ZQelf-5.gz`? Is ZQ trained on existing ELF weights (all weights or freezed some)?

**Comment by breakwa11** [comment]
@ivysrono done
