### ISSUE TITLE
能否加入 Leela0110 160k po

### ISSUE THREAD

**Issue by ivysrono** [breakwa11/GoAIRatings#4]
我测了下，同硬件下，Leela0110的16万po的时间，与40B的1600po的时间，和ELFv1的3200po的时间，很近似，不知能否加入以衡量实力。

**Comment by breakwa11** [comment]
到底什么硬件？什么样的显卡及CPU，时间具体多少秒左右？

**Comment by ivysrono** [comment]
CPU only，i5-8500，1min 左右。

**Comment by breakwa11** [comment]
所以，你所说的时间近似在我这不存在，而且时间近似也不能成为测试的理由

**Comment by ivysrono** [comment]
那算了，打扰。
